# -*- coding: utf-8 -*-
"""编排 (契约「build 编排 / 分块 / two_pads 锚 / sung 外部锚」): ``build(meta, out_dir, solve=)``。

产物: GDS (+ ``<stem>.gds.png`` 预览) + mesh + Palace config + manifest (输入 sha256); ``extract.blocks``
时另派生 ``block_<name>.geo`` (只含该块 component 的 Physical 组, 其余组整行
删除 —— 几何留作孤儿面, build_mesh 会清) + 各块 mesh/config。

几何源二选一: ``meta.geo`` 手写 ``.geo``, 或 ``meta.layout`` 版图 → ``compile_layout``
编译成 Layout (可调用几何源, 记账 qubits / subsystems 并入 circuit_model / results); 分块时
``Layout.for_block`` 在模型内按 component 过滤, 不派生 ``.geo``。

分块是 quasi-lumped 近似 (SPEC「切块纪律」): 跨块直接互容 = 结构性零。
廉价防线 (docs/physics.md §11): 不同块且从不共现的导体对若几何邻近
(bbox 间距 < airbox.side_um) 则 warn —— 有意直接耦合的导体对必须同块共现。

``solve=True``: 跑 Palace (env ``PALACE_BIN``, ⚠ ``HWLOC_COMPONENTS=-gl``
在 WSL 必须; ``QDSL_PALACE_NP`` 控 rank 数, 默认 1) → parse_capacitance →
circuit_model (meta 的 E_J 系频率 Hz = E_J/h, 此处 ×h 转焦耳) →
``results.yaml`` (hamiltonian + capacitance); meta 有 ``targets:`` 时另有 ``validation`` 段 (只核对整片)。

``converge(meta, out_dir, scales)``: 网格收敛扫描 —— mesh 尺寸同比缩放, 每档整片求解一次,
``convergence.yaml`` 记最细两档每个 C 元素 / hamiltonian 字段的相对变化 (docs/physics.md §6:
单网格数字没有误差棒)。
"""

from __future__ import annotations

import glob
import hashlib
import math
import os
import re
import subprocess
import warnings
from dataclasses import asdict, replace
from itertools import combinations
from pathlib import Path

import yaml

from .circuit_model import H_PLANCK, solve_circuit_model
from .errors import QuantumDslError
from .gds import build_gds, gds_map, jj_gds_layers, render_gds_png
from .geo import parse_physical_name
from .mesh import build_mesh
from .meta import Meta, load_meta
from .palace import palace_config, parse_capacitance

__all__ = ["build", "converge"]

_PHYS_LINE = re.compile(r'Physical\s+Surface\s*\(\s*"([^"]+)"')


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _palace_bin() -> str:
    binpath = os.environ.get("PALACE_BIN")
    if not binpath:
        hits = sorted(glob.glob(os.path.expanduser(
            "~/spack/opt/spack/*/palace-*/bin/palace")))
        binpath = hits[-1] if hits else ""
    if not binpath or not Path(binpath).is_file():
        raise QuantumDslError(
            "build(solve=True): Palace binary not found — set PALACE_BIN")
    return binpath


def _run_palace(cfg_path: Path) -> None:
    # ⚠ hwloc 的 gl 插件 TCP 探测 X display 会把 MPI_Init 挂死在 WSL2 上。
    env = dict(os.environ, HWLOC_COMPONENTS="-gl")
    n_rank = env.get("QDSL_PALACE_NP", "1")
    r = subprocess.run([_palace_bin(), "-np", n_rank, cfg_path.name],
                       cwd=cfg_path.parent, env=env,
                       capture_output=True, text=True)
    if r.returncode != 0:
        raise QuantumDslError(
            f"palace failed rc={r.returncode} on {cfg_path}\n"
            f"--- stdout tail ---\n{r.stdout[-2000:]}\n"
            f"--- stderr tail ---\n{r.stderr[-2000:]}")


def _junctions_from_meta(circuit_model: dict) -> list[dict]:
    """meta 的 qubits 词汇 → solve_circuit_model 的 junction dicts。
    load_meta 已把 E_J/E_J1/E_J2 解析成 **Hz** (E_J/h) —— 这里 ×h 转焦耳。"""
    junctions = []
    for q in circuit_model.get("qubits", []):
        name = q.get("name")
        if "islands" in q:
            islands = list(q["islands"])
        elif "island" in q:
            islands = [q["island"]]
        else:
            raise QuantumDslError(
                f"build: circuit_model qubit {name!r} needs island: X or "
                f"islands: [a, b]")
        j: dict = {"name": name, "islands": islands}
        if "L_J" in q:
            j["L_J"] = q["L_J"]                       # 已是亨利 (SI)
        if "E_J" in q:
            j["E_J"] = q["E_J"] * H_PLANCK            # Hz → 焦耳
        if "squid" in q:
            s = q["squid"]
            j["squid"] = {"E_J1": s["E_J1"] * H_PLANCK,
                          "E_J2": s["E_J2"] * H_PLANCK,
                          "flux": s.get("flux", 0.0)}
        junctions.append(j)
    return junctions


def _write_block_geo(src: Path, components, dst: Path) -> None:
    """块派生: 只保留 component ∈ 块的 Physical 行, 其余 Physical 行整行删。
    几何语句原样保留 (孤儿面由 build_mesh 清理); Include 的库文件不复制 ——
    含 Include 的版图分块时块文件与源同目录才可解析 (仓内例子不含)。"""
    keep = set(components)
    out_lines = [f"// derived block ({', '.join(sorted(keep))}) — "
                 f"generated by quantum_dsl.build from {src.name}"]
    for line in src.read_text(encoding="utf-8").splitlines():
        m = _PHYS_LINE.search(line.split("//", 1)[0])   # 注释里的示例名不算
        if m and parse_physical_name(m.group(1)).component not in keep:
            continue
        out_lines.append(line)
    dst.write_text("\n".join(out_lines) + "\n", encoding="utf-8")


def _bbox_gap_um(a, b) -> float:
    dx = max(0.0, a[0] - b[2], b[0] - a[2])
    dy = max(0.0, a[1] - b[3], b[1] - a[3])
    return math.hypot(dx, dy)


def _warn_overlapping_blocks(blocks) -> None:
    """块集合本该切分芯片。重叠 = 同一导体在多块里**整块**重新求解, 其自电容会被
    ``assemble()`` 按共享节点无条件累加 (跨切口的共享节点才是它的本意) —— 这样的块
    只能单独读, 不能拼。"""
    where: dict = {}
    for blk in blocks:
        for c in blk["components"]:
            where.setdefault(c, []).append(blk.get("name"))
    dup = {c: bs for c, bs in where.items() if len(bs) > 1}
    if dup:
        warnings.warn(
            "extract.blocks: " + "; ".join(
                f"{c!r} appears in {len(bs)} blocks ({', '.join(map(str, bs))})"
                for c, bs in sorted(dup.items())[:6])
            + (" …" if len(dup) > 6 else "")
            + " — the blocks overlap instead of partitioning the chip, so each block "
              "re-solves that conductor in full. Read such blocks one at a time; passing "
              "them to assemble() double-counts the shared conductors' self-capacitance. "
              "Note also that every block drops the conductors outside it, so neighbours "
              "that sit close to a kept conductor are absent from its solved environment.",
            stacklevel=3)


def _warn_structural_zero_coupling(blocks, bbox_by_comp, side_um) -> None:
    cohabit = set()
    for blk in blocks:
        for pair in combinations(sorted(blk["components"]), 2):
            cohabit.add(frozenset(pair))
    comps = sorted({c for blk in blocks for c in blk["components"]
                    if c in bbox_by_comp})
    for a, b in combinations(comps, 2):
        if frozenset((a, b)) in cohabit:
            continue
        gap = _bbox_gap_um(bbox_by_comp[a], bbox_by_comp[b])
        if gap < side_um:
            warnings.warn(
                f"extract.blocks: conductors {a!r} and {b!r} are "
                f"{gap:.1f} um apart (< airbox.side_um={side_um:g}) but never "
                f"co-solved in one block — their direct mutual capacitance is "
                f"structurally ZERO in the assembled model. If they couple by "
                f"design, put them in the same block.", stacklevel=3)


def _merge_qubits(meta_qubits: list, generated: list) -> list:
    """版图生成的 circuit_model.qubits 与 meta 手写的合并: 同名必须一致, 否则 raise。"""
    by_name = {q.get("name"): q for q in meta_qubits}
    merged = list(meta_qubits)
    for q in generated:
        if q["name"] in by_name:
            if by_name[q["name"]] != q:
                raise QuantumDslError(
                    f"build: circuit_model qubit {q['name']!r} is generated by the layout as "
                    f"{q} but meta says {by_name[q['name']]} — drop it from meta or make them agree")
        else:
            merged.append(q)
    return merged


def _results_doc(cap, subsystems, qubits) -> dict:
    """求解产物 ``results.yaml`` 的**唯一** schema (整片与分块共用)。
    调用方自己决定传哪些 subsystems / qubits (分块只传标签落在块里的那些)。"""
    doc: dict = {"capacitance": {"labels": list(cap.labels),
                                 "maxwell_fF": cap.maxwell_fF,
                                 "mutual_fF": cap.mutual_fF}}
    if subsystems:
        doc["subsystems"] = subsystems
    if qubits:
        model = solve_circuit_model(cap.labels, cap.maxwell_fF,
                                    _junctions_from_meta({"qubits": qubits}))
        doc["hamiltonian"] = {
            "method": model.method,
            "qubits": [{**asdict(q), "islands": list(q.islands)}
                       for q in model.qubits],
            "couplings": [asdict(c) for c in model.couplings],
        }
    return doc


def _check_target_names(targets, qubits) -> None:
    """targets 点的 qubit 名在网格化之前就查 (sung 级求解是小时级, 拼错名不能等解完才 raise)。"""
    known = {q.get("name") for q in qubits}
    for c in targets.get("checks", ()):
        missing = [n for n in ([c["qubit"]] if "qubit" in c else c["pair"]) if n not in known]
        if missing:
            raise QuantumDslError(f"build: targets name unknown qubit(s) {missing}; "
                                  f"circuit_model.qubits has {sorted(known)}")


def _validation(doc, targets) -> dict:
    """targets 对 results 文档逐项核对 → ``validation`` 段 (deviation = 实测/期望 − 1)。
    未命中只 warn: 偏差是要报的信息, 不是管线错误。"""
    ham = doc["hamiltonian"]
    qubits = {q["name"]: q for q in ham["qubits"]}
    pairs = {frozenset((c["qubit_a"], c["qubit_b"])): c for c in ham["couplings"]}
    rows = []
    for c in targets["checks"]:
        actual = (qubits[c["qubit"]] if "qubit" in c else pairs[frozenset(c["pair"])])[c["field"]]
        dev = actual / c["expected"] - 1.0
        rows.append({**c, "actual": actual, "deviation": dev, "pass": abs(dev) <= c["tol"]})
    missed = [r for r in rows if not r["pass"]]
    if missed:
        warnings.warn(f"targets: {len(missed)}/{len(rows)} missed — " + "; ".join(
            f"{r.get('qubit') or '~'.join(r['pair'])}.{r['field']} = {r['actual']:.4g} vs "
            f"{r['expected']:.4g} ({r['deviation']:+.1%}, tol ±{r['tol']:.0%})" for r in missed),
            stacklevel=3)
    return {"source": targets.get("source"), "passed": not missed, "checks": rows}


def _in_scope(items, labels, key) -> list:
    """只留下全部 island / net 都落在 ``labels`` 里的条目 (分块求解用)。"""
    out = []
    for it in items:
        need = set(it.get("islands") or ([it[key]] if it.get(key) else []))
        if need and need <= set(labels):
            out.append(it)
    return out


def build(meta, out_dir, solve: bool = False, blocks=None) -> dict:
    """meta (路径或 Meta) + 输出目录 → 产物路径 dict (键: gds/mesh/config/
    manifest[/blocks][/capacitance/results]; 有 gds 时另有 gds_png; 版图路线另有
    layout (Layout 记账: qubits / subsystems / ports))。

    ``blocks`` = ``extract.blocks`` 里的块名列表 (或 ``"all"``) 时**只做这些块**:
    跳过整片网格与 config (整片可能比单块大两个数量级, 本机跑不动), 于是 ``mesh`` /
    ``config`` 键不出现; ``solve=True`` 会逐块跑 Palace 并写 ``block_<name>.results.yaml``
    (schema 与整片的 ``results.yaml`` 相同), 结果挂在 ``result["blocks"][i]`` 上。
    ``blocks=None`` (默认) = 原行为: 整片 + 各块网格/config, 只求解整片。"""
    m = meta if isinstance(meta, Meta) else load_meta(meta)
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)

    result: dict = {}
    circuit_model = dict(m.circuit_model)
    subsystems = list(m.subsystems)
    if m.layout_path is not None:                     # 版图路线
        from .layout import compile_layout
        lay = compile_layout(m)
        src = lay
        stem = m.layout_path.name.split(".")[0]
        inputs = [m.path, *lay.inputs]
        circuit_model["qubits"] = _merge_qubits(
            list(circuit_model.get("qubits") or []), lay.qubits)
        subsystems += lay.subsystems
        result["layout"] = lay
    else:
        src, stem, inputs = m.geo_path, m.geo_path.stem, [m.path, m.geo_path]
    _check_target_names(m.targets, circuit_model.get("qubits") or [])

    blocks_spec = (m.extract or {}).get("blocks") or []
    if blocks is not None:
        names = [b.get("name") for b in blocks_spec]
        if not blocks_spec:
            raise QuantumDslError("build: blocks= given but meta has no extract.blocks")
        want = list(names) if blocks == "all" else list(blocks)
        unknown = [n for n in want if n not in names]
        if unknown:
            raise QuantumDslError(
                f"build: unknown block name(s) {unknown}; extract.blocks has {names}")
        blocks_spec = [b for b in blocks_spec if b.get("name") in want]

    outputs: list[Path] = []
    if gds_map(m):                          # 无 GDS 映射 = 不出 GDS 分叉
        result["gds"] = build_gds(src, m, out / f"{stem}.gds")
        result["gds_png"] = render_gds_png(
            result["gds"], out / f"{stem}.gds.png", jj_layers=jj_gds_layers(m))
        outputs += [result["gds"], result["gds_png"]]
    mesh = cfg_path = None
    if blocks is None:      # blocks= 指定时不出整片: 整片网格可能比单块大两个数量级
        mesh = build_mesh(src, m, out / f"{stem}.msh")
        cfg_path = out / f"{stem}.json"
        palace_config(mesh, m, cfg_path)
        result.update({"mesh": mesh.path, "config": cfg_path})
        outputs += [mesh.path, cfg_path]

    if blocks_spec:
        _warn_overlapping_blocks(blocks_spec)
        if mesh is not None:            # 邻近告警要整片的导体 bbox; blocks= 时没有
            _warn_structural_zero_coupling(blocks_spec, mesh.conductor_bbox_um,
                                           float(m.airbox.get("side_um", 0)))
        result["blocks"] = []
        for blk in blocks_spec:
            name, comps = blk.get("name"), list(blk.get("components") or ())
            if not name or not comps:
                raise QuantumDslError(
                    f"build: extract.blocks entries need name + components, "
                    f"got {blk!r}")
            if m.layout_path is not None:
                bgeo, bsrc = None, lay.for_block(comps)
            else:
                bgeo = bsrc = out / f"block_{name}.geo"
                _write_block_geo(m.geo_path, comps, bgeo)
            bmesh = build_mesh(bsrc, m, out / f"block_{name}.msh")
            if set(bmesh.labels) != set(comps):
                raise QuantumDslError(
                    f"build: block {name!r} asked for components {comps} but "
                    f"the derived geometry has metal nets "
                    f"{list(bmesh.labels)} — typo in components?")
            bcfg = out / f"block_{name}.json"
            palace_config(bmesh, m, bcfg, output=f"postpro_block_{name}")
            result["blocks"].append(
                {"name": name, "geo": bgeo, "mesh": bmesh.path, "config": bcfg,
                 "labels": bmesh.labels})
            outputs += ([bgeo] if bgeo else []) + [bmesh.path, bcfg]

    manifest_path = out / "manifest.yaml"
    manifest = {
        "schema": "quantum-dsl/manifest/1",
        "inputs": [{"path": str(p), "sha256": _sha256(Path(p))}
                   for p in dict.fromkeys(inputs)],
        "outputs": [{"path": str(p), "sha256": _sha256(Path(p))}
                    for p in outputs],
    }
    manifest_path.write_text(yaml.safe_dump(manifest, sort_keys=False),
                             encoding="utf-8")
    result["manifest"] = manifest_path

    if solve:
        all_qubits = list(circuit_model.get("qubits") or [])
        if cfg_path is not None:                       # 整片
            _run_palace(cfg_path)
            cap = parse_capacitance(out / "postpro", labels=mesh.labels)
            result["capacitance"] = cap
            doc = _results_doc(cap, subsystems, all_qubits)
            if m.targets:
                doc["validation"] = _validation(doc, m.targets)
            results_path = out / "results.yaml"
            results_path.write_text(yaml.safe_dump(doc, sort_keys=False, allow_unicode=True),
                                    encoding="utf-8")
            result["results"] = results_path
        elif m.targets:
            warnings.warn("build: meta targets are checked against whole-chip results only — "
                          "block results carry no validation section", stacklevel=2)
        for entry in result.get("blocks", []) if blocks is not None else []:
            _run_palace(entry["config"])
            bcap = parse_capacitance(out / f"postpro_block_{entry['name']}",
                                     labels=entry["labels"])
            entry["capacitance"] = bcap
            bres = out / f"block_{entry['name']}.results.yaml"
            bres.write_text(
                yaml.safe_dump(_results_doc(
                    bcap, _in_scope(subsystems, bcap.labels, "name"),
                    _in_scope(all_qubits, bcap.labels, "island")), sort_keys=False),
                encoding="utf-8")
            entry["results"] = bres
    return result


def _rel(a: float, b: float) -> float:
    return 0.0 if a == b else (b - a) / abs(b) if b else math.inf


def converge(meta, out_dir, scales=(1.0, 0.6)) -> dict:
    """网格收敛扫描 (issue #26): ``mesh.max_size_um`` / ``min_size_um`` 同乘每个 scale, 每档一次整片
    ``build(solve=True)`` 落在 ``out/mesh_x<s>/``; 最细两档的相对变化 (细 − 次细)/|细| 逐个 C 元素与
    hamiltonian 数值字段写进 ``out/convergence.yaml``。返回 ``{runs: [build 结果…], convergence: path, doc}``。
    代价 = 各档求解之和, 细档单元数 ∝ s⁻³ (0.6 ≈ ×4.6); ``PALACE_BIN=tools/palace_remote.sh`` 同样适用。
    只缩放尺寸 (h 加密), 边缘细化渐变区 10 → 130 µm 与 order 不动。"""
    m = meta if isinstance(meta, Meta) else load_meta(meta)
    ss = sorted({float(s) for s in scales}, reverse=True)
    if len(ss) < 2 or ss[-1] <= 0:
        raise QuantumDslError(f"converge: need >= 2 distinct positive scales, got {scales!r}")
    if not {"max_size_um", "min_size_um"} <= set(m.mesh):
        raise QuantumDslError("converge: meta.mesh needs max_size_um and min_size_um")
    out = Path(out_dir)
    runs, docs, rows = [], [], []
    for s in ss:
        sizes = {k: s * float(m.mesh[k]) for k in ("max_size_um", "min_size_um")}
        r = build(replace(m, mesh={**m.mesh, **sizes}), out / f"mesh_x{s:g}", solve=True)
        runs.append(r)
        docs.append(yaml.safe_load(Path(r["results"]).read_text(encoding="utf-8")))
        rows.append({"scale": s, **sizes, "results": str(r["results"])})

    a, b = docs[-2], docs[-1]
    doc: dict = {"runs": rows, "compared": ss[-2:], "capacitance": {
        "labels": b["capacitance"]["labels"],
        "maxwell_rel_change": [[_rel(x, y) for x, y in zip(ra, rb)] for ra, rb in
                               zip(a["capacitance"]["maxwell_fF"], b["capacitance"]["maxwell_fF"])]}}
    if "hamiltonian" in b:
        ha, hb = a["hamiltonian"], b["hamiltonian"]
        doc["hamiltonian"] = {
            "qubits": {qb["name"]: {k: _rel(qa[k], v) for k, v in qb.items() if isinstance(v, float)}
                       for qa, qb in zip(ha["qubits"], hb["qubits"])},
            "couplings": [{"pair": [cb["qubit_a"], cb["qubit_b"]],
                           **{k: _rel(ca[k], cb[k]) for k in ("beta", "g_MHz")}}
                          for ca, cb in zip(ha["couplings"], hb["couplings"])]}
    path = out / "convergence.yaml"
    path.write_text(yaml.safe_dump(doc, sort_keys=False, allow_unicode=True), encoding="utf-8")
    return {"runs": runs, "convergence": path, "doc": doc}
