# -*- coding: utf-8 -*-
"""编排 (契约 N13/N14/N7/N15): ``build(meta, out_dir, solve=)``。

产物: GDS + mesh + Palace config + manifest (输入 sha256); ``extract.blocks``
时另派生 ``block_<name>.geo`` (只含该块 component 的 Physical 组, 其余组整行
删除 —— 几何留作孤儿面, build_mesh 会清) + 各块 mesh/config。

分块是 quasi-lumped 近似 (SPEC「切块纪律」): 跨块直接互容 = 结构性零。
廉价防线 (pipeline §11): 不同块且从不同块共现的导体对若几何邻近
(bbox 间距 < airbox.side_um) 则 warn —— 有意直接耦合的导体对必须同块共现。

``solve=True``: 跑 Palace (env ``PALACE_BIN``, ⚠ ``HWLOC_COMPONENTS=-gl``
在 WSL 必须; ``QDSL_PALACE_NP`` 控 rank 数, 默认 1) → parse_capacitance →
circuit_model (meta 的 E_J 系频率 Hz = E_J/h, 此处 ×h 转焦耳) →
``results.yaml`` (hamiltonian + capacitance)。
"""

from __future__ import annotations

import glob
import hashlib
import math
import os
import re
import subprocess
import warnings
from dataclasses import asdict
from itertools import combinations
from pathlib import Path

import yaml

from .circuit_model import H_PLANCK, solve_circuit_model
from .errors import QuantumDslError
from .gds import build_gds
from .geo import parse_physical_name
from .mesh import build_mesh
from .meta import Meta, load_meta
from .palace import palace_config, parse_capacitance

__all__ = ["build"]

_PHYS_LINE = re.compile(r'Physical\s+Surface\s*\(\s*"([^"]+)"')


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _palace_bin() -> str:
    binpath = os.environ.get("PALACE_BIN")
    if not binpath:
        hits = sorted(glob.glob(os.path.expanduser(
            "~/spack/opt/spack/*/palace-*/bin/palace")))
        binpath = hits[-1] if hits else ""
    if not binpath or not Path(binpath).is_file():
        raise QuantumDslError(
            "build(solve=True): Palace binary not found — set PALACE_BIN")
    return binpath


def _run_palace(cfg_path: Path) -> None:
    # ⚠ hwloc 的 gl 插件 TCP 探测 X display 会把 MPI_Init 挂死在 WSL2 上。
    env = dict(os.environ, HWLOC_COMPONENTS="-gl")
    n_rank = env.get("QDSL_PALACE_NP", "1")
    r = subprocess.run([_palace_bin(), "-np", n_rank, cfg_path.name],
                       cwd=cfg_path.parent, env=env,
                       capture_output=True, text=True)
    if r.returncode != 0:
        raise QuantumDslError(
            f"palace failed rc={r.returncode} on {cfg_path}\n"
            f"--- stdout tail ---\n{r.stdout[-2000:]}\n"
            f"--- stderr tail ---\n{r.stderr[-2000:]}")


def _junctions_from_meta(circuit_model: dict) -> list[dict]:
    """meta 的 qubits 词汇 → solve_circuit_model 的 junction dicts。
    load_meta 已把 E_J/E_J1/E_J2 解析成 **Hz** (E_J/h) —— 这里 ×h 转焦耳。"""
    junctions = []
    for q in circuit_model.get("qubits", []):
        name = q.get("name")
        if "islands" in q:
            islands = list(q["islands"])
        elif "island" in q:
            islands = [q["island"]]
        else:
            raise QuantumDslError(
                f"build: circuit_model qubit {name!r} needs island: X or "
                f"islands: [a, b]")
        j: dict = {"name": name, "islands": islands}
        if "L_J" in q:
            j["L_J"] = q["L_J"]                       # 已是亨利 (SI)
        if "E_J" in q:
            j["E_J"] = q["E_J"] * H_PLANCK            # Hz → 焦耳
        if "squid" in q:
            s = q["squid"]
            j["squid"] = {"E_J1": s["E_J1"] * H_PLANCK,
                          "E_J2": s["E_J2"] * H_PLANCK,
                          "flux": s.get("flux", 0.0)}
        junctions.append(j)
    return junctions


def _write_block_geo(src: Path, components, dst: Path) -> None:
    """块派生: 只保留 component ∈ 块的 Physical 行, 其余 Physical 行整行删。
    几何语句原样保留 (孤儿面由 build_mesh 清理); Include 的库文件不复制 ——
    含 Include 的版图分块时块文件与源同目录才可解析 (contract fixtures 不含)。"""
    keep = set(components)
    out_lines = [f"// derived block ({', '.join(sorted(keep))}) — "
                 f"generated by quantum_dsl.build from {src.name}"]
    for line in src.read_text(encoding="utf-8").splitlines():
        m = _PHYS_LINE.search(line)
        if m and parse_physical_name(m.group(1)).component not in keep:
            continue
        out_lines.append(line)
    dst.write_text("\n".join(out_lines) + "\n", encoding="utf-8")


def _bbox_gap_um(a, b) -> float:
    dx = max(0.0, a[0] - b[2], b[0] - a[2])
    dy = max(0.0, a[1] - b[3], b[1] - a[3])
    return math.hypot(dx, dy)


def _warn_structural_zero_coupling(blocks, bbox_by_comp, side_um) -> None:
    cohabit = set()
    for blk in blocks:
        for pair in combinations(sorted(blk["components"]), 2):
            cohabit.add(frozenset(pair))
    comps = sorted({c for blk in blocks for c in blk["components"]
                    if c in bbox_by_comp})
    for a, b in combinations(comps, 2):
        if frozenset((a, b)) in cohabit:
            continue
        gap = _bbox_gap_um(bbox_by_comp[a], bbox_by_comp[b])
        if gap < side_um:
            warnings.warn(
                f"extract.blocks: conductors {a!r} and {b!r} are "
                f"{gap:.1f} um apart (< airbox.side_um={side_um:g}) but never "
                f"co-solved in one block — their direct mutual capacitance is "
                f"structurally ZERO in the assembled model. If they couple by "
                f"design, put them in the same block.", stacklevel=3)


def build(meta, out_dir, solve: bool = False) -> dict:
    """meta (路径或 Meta) + 输出目录 → 产物路径 dict (键: gds/mesh/config/
    manifest[/blocks][/capacitance/results])。"""
    m = meta if isinstance(meta, Meta) else load_meta(meta)
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    stem = m.geo_path.stem

    result: dict = {}
    outputs: list[Path] = []
    if (m.gds or {}).get("by_role"):        # 未声明 by_role = 不出 GDS 分叉
        result["gds"] = build_gds(m.geo_path, m, out / f"{stem}.gds")
        outputs.append(result["gds"])
    mesh = build_mesh(m.geo_path, m, out / f"{stem}.msh")
    cfg_path = out / f"{stem}.json"
    palace_config(mesh, m, cfg_path)
    result.update({"mesh": mesh.path, "config": cfg_path})
    outputs += [mesh.path, cfg_path]

    blocks_spec = (m.extract or {}).get("blocks") or []
    if blocks_spec:
        side_um = float(m.airbox.get("side_um", 0))
        _warn_structural_zero_coupling(blocks_spec, mesh.conductor_bbox_um,
                                       side_um)
        result["blocks"] = []
        for blk in blocks_spec:
            name, comps = blk.get("name"), list(blk.get("components") or ())
            if not name or not comps:
                raise QuantumDslError(
                    f"build: extract.blocks entries need name + components, "
                    f"got {blk!r}")
            bgeo = out / f"block_{name}.geo"
            _write_block_geo(m.geo_path, comps, bgeo)
            bmesh = build_mesh(bgeo, m, out / f"block_{name}.msh")
            if set(bmesh.labels) != set(comps):
                raise QuantumDslError(
                    f"build: block {name!r} asked for components {comps} but "
                    f"the derived geometry has metal nets "
                    f"{list(bmesh.labels)} — typo in components?")
            bcfg = out / f"block_{name}.json"
            palace_config(bmesh, m, bcfg)
            result["blocks"].append(
                {"name": name, "geo": bgeo, "mesh": bmesh.path, "config": bcfg})
            outputs += [bgeo, bmesh.path, bcfg]

    manifest_path = out / "manifest.yaml"
    manifest = {
        "schema": "quantum-dsl/manifest/1",
        "inputs": [{"path": str(p), "sha256": _sha256(p)}
                   for p in (m.path, m.geo_path)],
        "outputs": [{"path": str(p), "sha256": _sha256(Path(p))}
                    for p in outputs],
    }
    manifest_path.write_text(yaml.safe_dump(manifest, sort_keys=False),
                             encoding="utf-8")
    result["manifest"] = manifest_path

    if solve:
        _run_palace(cfg_path)
        cap = parse_capacitance(out / "postpro", labels=mesh.labels)
        result["capacitance"] = cap
        doc: dict = {"capacitance": {"labels": list(cap.labels),
                                     "maxwell_fF": cap.maxwell_fF,
                                     "mutual_fF": cap.mutual_fF}}
        if m.circuit_model.get("qubits"):
            model = solve_circuit_model(
                cap.labels, cap.maxwell_fF,
                _junctions_from_meta(m.circuit_model))
            doc["hamiltonian"] = {
                "method": model.method,
                "qubits": [{**asdict(q), "islands": list(q.islands)}
                           for q in model.qubits],
                "couplings": [asdict(c) for c in model.couplings],
            }
        results_path = out / "results.yaml"
        results_path.write_text(yaml.safe_dump(doc, sort_keys=False),
                                encoding="utf-8")
        result["results"] = results_path
    return result
