# -*- coding: utf-8 -*-
"""参数化 cell (契约 N12): 圆角多边形 + ``.geo`` 文本发射。

* ``rounded_polygon``: shapely 负/正 buffer 往返 (erode r → dilate r, 圆弧
  join) 预采样圆角 —— 凸角变成内接采样弧 (quad_segs=16, 面积亏 ≪1%)。
  半径过大把多边形吃没/切碎时 raise, 不静默。
* ``emit_geo``: 纯文本发射 OCC ``.geo`` (Point/Line/Curve Loop/Plane
  Surface + 四段 Physical 名), ``load_geo`` 可回读 (契约闭环, 名字合法性
  直接复用 parse_physical_name 校验)。
"""

from __future__ import annotations

import math

from .errors import QuantumDslError
from .geo import parse_physical_name

__all__ = ["rounded_polygon", "emit_geo"]

_CELL_KEYS = frozenset({"component", "layer", "role", "points",
                        "corner_radius_um", "primitive"})


def rounded_polygon(points, radius_um) -> list[tuple[float, float]]:
    """多边形顶点 (µm) + 圆角半径 → 采样后的顶点列表 (µm)。"""
    if not isinstance(radius_um, (int, float)) or isinstance(radius_um, bool) \
            or not math.isfinite(radius_um) or radius_um < 0:
        raise QuantumDslError(
            f"rounded_polygon: radius_um must be a finite number >= 0, "
            f"got {radius_um!r}")
    pts = [(float(x), float(y)) for x, y in points]
    if len(pts) < 3:
        raise QuantumDslError(
            f"rounded_polygon: need >= 3 points, got {len(pts)}")
    if radius_um == 0:
        return pts

    from shapely.geometry import Polygon   # 惰性: import quantum_dsl 保持轻量

    poly = Polygon(pts)
    if not poly.is_valid or poly.area <= 0:
        raise QuantumDslError(
            "rounded_polygon: input polygon is invalid or degenerate")
    rounded = poly.buffer(-radius_um, quad_segs=16).buffer(radius_um,
                                                           quad_segs=16)
    if rounded.is_empty or rounded.geom_type != "Polygon":
        raise QuantumDslError(
            f"rounded_polygon: radius {radius_um} um is too large for this "
            f"polygon (erosion left {rounded.geom_type or 'nothing'})")
    return [(float(x), float(y)) for x, y in rounded.exterior.coords[:-1]]


def emit_geo(cells) -> str:
    """cell dict 列表 → OCC ``.geo`` 文本 (load_geo 可回读)。

    cell 词汇: ``component`` (必填), ``points`` (必填, µm), ``layer`` (默认 1),
    ``role`` (默认 metal), ``corner_radius_um`` (默认 0), ``primitive``
    (默认 polygon)。
    """
    if not cells:
        raise QuantumDslError("emit_geo: needs >= 1 cell")
    lines = ['// generated by quantum_dsl.emit_geo — units: um',
             'SetFactory("OpenCASCADE");']
    n_pt = n_ln = n_loop = n_surf = 0
    for cell in cells:
        if not isinstance(cell, dict):
            raise QuantumDslError(f"emit_geo: cells must be dicts, got {cell!r}")
        unknown = sorted(set(cell) - _CELL_KEYS)
        if unknown:
            raise QuantumDslError(
                f"emit_geo: cell {cell.get('component')!r}: unknown key(s) "
                f"{unknown} (known: {sorted(_CELL_KEYS)})")
        component = cell.get("component")
        role = cell.get("role", "metal")
        layer = cell.get("layer", 1)
        primitive = cell.get("primitive", "polygon")
        name = f"{role}::{layer}::{component}::{primitive}"
        parse_physical_name(name)          # 名字合法性与 load_geo 同一把尺
        pts = rounded_polygon(cell.get("points") or (),
                              cell.get("corner_radius_um", 0))

        first_pt = n_pt + 1
        for x, y in pts:
            n_pt += 1
            lines.append(f"Point({n_pt}) = {{{x!r}, {y!r}, 0}};")
        first_ln = n_ln + 1
        for i in range(len(pts)):
            n_ln += 1
            a = first_pt + i
            b = first_pt + (i + 1) % len(pts)
            lines.append(f"Line({n_ln}) = {{{a}, {b}}};")
        n_loop += 1
        loop = ", ".join(str(t) for t in range(first_ln, n_ln + 1))
        lines.append(f"Curve Loop({n_loop}) = {{{loop}}};")
        n_surf += 1
        lines.append(f"Plane Surface({n_surf}) = {{{n_loop}}};")
        lines.append(f'Physical Surface("{name}") = {{{n_surf}}};')
    return "\n".join(lines) + "\n"
